modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Bug1312/CloudyPorkchops/issues"
[[mods]]
modId="cloudyporkchops"
version="0.0.0"
displayName="Cloudy Porkchops"
displayURL="SomeModrinthLinkOrSomething"
logoFile="pack.png"
authors="Bug1312, rainbowdestiny"
description='''Cloudy with a Chance of Meatballs lands into Minecraft with this fun and exciting mod!'''

[[dependencies.cloudy_porkchops]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cloudy_porkchops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
